# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: EverCraftKata Typescript Node.js CI

on:
  pull_request:
    branches:
    - master
    - dev
    paths: 
    - 'EverCraftKata/TypeScript/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Check Out
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install
      working-directory: ./EverCraftKata/TypeScript/
      run: npm ci

    - name: npm run test suite
      working-directory: ./EverCraftKata/TypeScript/
      run: npm run jest
